import "./Portfolio.css";

const Portfolio = () => {
  return (
    <>
      <div className="container-fluid padding-side text-white">
        <div className="row flex-column gap-5 align-items-center">
          <div className="col-lg-10">
            <h1
              className="banner-size fw-medium display-1 mb-4"
              data-aos="fade-up"
              data-aos-duration="1200"
            >
              Dive Into<span className="text-primary"> My Works </span>
            </h1>

            <p data-aos="fade-up" data-aos-duration="1400">
              Showcasing innovative, high-quality projects built with passion
              and precision.
            </p>
          </div>
          <div
            className="row col-lg-10"
            data-aos="fade-up"
            data-aos-duration="1400"
          >
            <h1>IRIS Software</h1>
            <div>
              <h2>Transaction Code Management System</h2>
              <ul>
                <li>
                  Developed and maintained a transaction management system using{" "}
                  <strong>Node.js</strong> and <strong>Angular</strong>.
                </li>
                <li>
                  Designed and implemented front-end{" "}
                  <strong>UI components</strong> and back-end{" "}
                  <strong>APIs</strong>.
                </li>
                <li>
                  Worked collaboratively with developers to ensure seamless
                  integration and performance optimization.
                </li>
              </ul>
            </div>
            <div>
              <h2>New and Known TCode Reconcilation System</h2>
              <ul>
                <li>
                  Developed and maintained a transaction management system using{" "}
                  <strong>Node.js</strong> and <strong>React</strong>.
                </li>
                <li>
                  Designed and implemented front-end{" "}
                  <strong>UI components</strong> and back-end{" "}
                  <strong>APIs</strong>.
                </li>
                <li>
                  Application gather different Tcode generated by Customer of
                  different region and different sources.
                </li>
                <li>
                  We reconcile then generate report and show result on UI with
                  different aspect
                </li>
              </ul>
            </div>
          </div>
          <div
            className="row col-lg-10"
            data-aos="fade-up"
            data-aos-duration="1400"
          >
            <h1>EdgeVerve Systems Limited</h1>
            <h2>ABCD (Anybody Can Code) Platform</h2>
            <ul>
              <li>
                Built a low-code/no-code application using Loopback and
                PolymerJS for banking automation.
                <strong>Node.js</strong> and <strong>React</strong>.
              </li>
              <li>
                Developed dynamic form generation and script creation tools for
                banking product customization.
                <strong>UI components</strong> and back-end{" "}
                <strong>APIs</strong>.
              </li>
            </ul>
            <h2>Document Management System</h2>
            <ul>
              <li>
                Lead a team of four in implementing Alfresco-based document
                management for an Australian bank.
              </li>
              <li>
                Developed API integrations and custom document templates using
                Java, CMIS APIs, and shell scripting.
              </li>
            </ul>
            <h2>Automation & Machine Learning Projects</h2>
            <ul>
              <li>
                Developed Release Note Generation Tool to automate documentation
                using Python and Jenkins
              </li>
              <li>
                Created Patch Building Tool to automate patch deployment and
                save manual effort.
              </li>
              <li>
                Implemented Defaulter Prediction model using ML algorithms to
                forecast potential bank defaulters with 60% accuracy.
              </li>
              <li>
                Worked on Loan Prediction System to enhance customer targeting
                for personal loans, increasing loan conversions by 20%.
              </li>
            </ul>
          </div>
          <div
            className="row col-lg-10"
            data-aos="fade-up"
            data-aos-duration="1400"
          >
            <h1>Nexm Software Pvt. Ltd.</h1>
            <h2>Follow Chess (Android & iOS App)</h2>
            <ul>
              <li>
                Contributed to the enhancement of a live chess-tracking app with
                100K+ downloads.
              </li>
              <li>
                Implemented real-time chess event streaming and game analysis
                features
              </li>
            </ul>
            <h2>Analyze This Chess (iOS App)</h2>
            <ul>
              <li>
                Integrated open-source chess engine Stockfish for move analysis
                and performance improvement
              </li>
              <li>
                Enabled compatibility with Objective-C, enhancing the iOS user
                experience
              </li>
            </ul>
          </div>
          <div
            className="row col-lg-10"
            data-aos="fade-up"
            data-aos-duration="1400"
          >
            <h1>Innotical Solutions Pvt. Ltd</h1>
            <div>
              <h2>Game Developement</h2>
              <ul>
                <li>
                  Led a team of 3 in developing cross-platform mobile games
                  using C++ (Cocos2d-x).
                </li>
                <li>
                  Integrated social media leaderboards (Facebook, Google Play)
                  to enhance user engagement.
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Portfolio;
